# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios, '9.0'
pod 'AFNetworking'

target 'gsearch' do

end

target 'gsearchTests' do

end

target 'gsearchUITests' do

end

